---
# handlers file for deploy-sonar
- name: "restart SonarQube service"
  service:
    name: sonar
    state: restarted

- name: "fail if expected sonar version not confirmed"
  fail:
    msg: Please check if 'Version' field of http://{{ inventory_hostname }}{{ sonar_web_context }} match to {{ sonar_version }}

- name: "warn about post-upgrade steps"
  debug:
    msg:
      - "SonarQube version changed to {{ sonar_version }} but additional actions required from your side"
      - "Visit http://{{ inventory_hostname }}{{ sonar_web_context }}/setup to follow the post-upgrade procedure"

- name: enable postgresql
  service: name=postgresql enabled=yes

- name: start postgresql
  service: name=postgresql state=started

- name: stop postgresql
  service: name=postgresql state=stopped

- name: restart postgresql
  service: name=postgresql state=restarted

- name: reload postgresql
  service: name=postgresql state=reloaded