---
# tasks file for ansible-role-sonarqube/

- name: "Create SonarQube system group"
  group:
    name: "{{ sonar_group }}"
    state: present

- name: "Create SonarQube system user"
  user:
    name: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    createhome: no
    shell: "/sbin/nologin"
    comment: "SonarQube System user"
    state: present

- name: "Create SonarQube directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    mode: "u=rwx,g=rx,o="
  with_items:
    - "{{ sonar_install_directory }}"
    - "{{ sonar_logs_dir }}"
    - "{{ sonar_data_dir }}"
    - "{{ sonar_temp_dir }}"

- name: "set max_map_count value (required by elasticsearch)"
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present

- name: "set fs.file-max value (required by elasticsearch)"
  sysctl:
    name: fs.file-max
    value: 65536
    state: present

- name: Add a line to a file if the file does not exist, without passing regexp
  ansible.builtin.blockinfile:
    path:  /etc/sysctl.conf
    block:  |
      ulimit -n 65536
      ulimit -u 4096

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - vim
    - net-tools

- name: Install openjdk-17-jdk
  ansible.builtin.apt:
    name: openjdk-17-jre
    state: present
    update_cache: yes